### PR TITLE
Resolves #625 - Add support for the className prop for the Column component

### LINKED ISSUE #625: Column component cannot be re-styled using `<Box/>` or `styled-components`
## 🐛 Bug report

**Current Behavior**
```
<Box as={Column} display={['none', 'block']} />
```

Styles are not passed on to the `Column` correctly. Similarly, overriding does not work when using `styled-components`:

```
const StyledColumn = styled(Column)`
  display: none;
`
```

**Expected behavior**

`<Box/>` and `styled-components` should work with all Matchbox components.

**Reproducible example**

See above example.

**Suggested solution(s)**

I believe the `className` prop just needs to be exposed on the component for this to work.

### PR DESCRIPTION
**Pull request by nicklemmon**
Resolves #625 

### What Changed

- `className` accepted as a prop for the `<Column/>` component

### How To Test or Verify

- On the Storybook site, try:
```js
<Box as={Column} display="none">I am invisible!</Box>
```

### PR Checklist

- [ ] Incorporate feedback

### CODE REVIEW

File: packages/matchbox/src/components/Column/Column.js [hunk 1]
```diff
@@ -46,6 +47,7 @@ Column.displayName = 'Column';
 Column.propTypes = {
   children: PropTypes.node,
   width: PropTypes.oneOfType([PropTypes.oneOf(['content']), PropTypes.number]),
+  className: PropTypes.string,
```
Comment (jonambas) [inline packages/matchbox/src/components/Column/Column.js:50]: I think this works. For your use case you could expose `display`

```jsx
import { display } from 'styled-system`;
import { createPropTypes } from '@styled-system/prop-types';

...

const { width, children, className, display } = props;

...

<StyledColumn display={display} />

...

Column.propTypes = {
  ...createPropTypes(display.propNames),
}

```

**Review by jonambas — APPROVED** [review]
Looks good, but added a suggestion

File: packages/matchbox/src/components/Column/Column.js (hunk 1 above)
Comment (jonambas) [reply packages/matchbox/src/components/Column/Column.js:50]: `styled(Box)` already includes `display` so no need to add it to the `StyledColumn` declaration

**Review by jonambas — APPROVED** [review]
LGTM
